# BALL Build Docker Image, by H.-Philipp Brachvogel 07.07.2015

FROM ubuntu_1404_ball_bare

RUN apt-get -y install libboost-all-dev flex bison qt4-default libtbb-dev libeigen3-dev libglew-dev sip-dev libfftw3-dev

