# BALL Build Docker Image, by H.-Philipp Brachvogel 07.07.2015

FROM centos_6_ball_bare

RUN yum -y install boost-devel sip-devel qt-devel tbb-devel

RUN yum -y install epel-release

RUN yum -y install eigen3-devel qtwebkit-devel glew-devel
 

